# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/adam/github/computational-geometry

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/adam/github/computational-geometry

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/adam/github/computational-geometry/CMakeFiles /home/adam/github/computational-geometry/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/adam/github/computational-geometry/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named DrawPolygon

# Build rule for target.
DrawPolygon: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 DrawPolygon
.PHONY : DrawPolygon

# fast build rule for target.
DrawPolygon/fast:
	$(MAKE) -f CMakeFiles/DrawPolygon.dir/build.make CMakeFiles/DrawPolygon.dir/build
.PHONY : DrawPolygon/fast

#=============================================================================
# Target rules for targets named PolygonIntersection

# Build rule for target.
PolygonIntersection: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 PolygonIntersection
.PHONY : PolygonIntersection

# fast build rule for target.
PolygonIntersection/fast:
	$(MAKE) -f CMakeFiles/PolygonIntersection.dir/build.make CMakeFiles/PolygonIntersection.dir/build
.PHONY : PolygonIntersection/fast

#=============================================================================
# Target rules for targets named PolygonUnion

# Build rule for target.
PolygonUnion: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 PolygonUnion
.PHONY : PolygonUnion

# fast build rule for target.
PolygonUnion/fast:
	$(MAKE) -f CMakeFiles/PolygonUnion.dir/build.make CMakeFiles/PolygonUnion.dir/build
.PHONY : PolygonUnion/fast

draw_polygon.o: draw_polygon.cpp.o
.PHONY : draw_polygon.o

# target to build an object file
draw_polygon.cpp.o:
	$(MAKE) -f CMakeFiles/DrawPolygon.dir/build.make CMakeFiles/DrawPolygon.dir/draw_polygon.cpp.o
.PHONY : draw_polygon.cpp.o

draw_polygon.i: draw_polygon.cpp.i
.PHONY : draw_polygon.i

# target to preprocess a source file
draw_polygon.cpp.i:
	$(MAKE) -f CMakeFiles/DrawPolygon.dir/build.make CMakeFiles/DrawPolygon.dir/draw_polygon.cpp.i
.PHONY : draw_polygon.cpp.i

draw_polygon.s: draw_polygon.cpp.s
.PHONY : draw_polygon.s

# target to generate assembly for a file
draw_polygon.cpp.s:
	$(MAKE) -f CMakeFiles/DrawPolygon.dir/build.make CMakeFiles/DrawPolygon.dir/draw_polygon.cpp.s
.PHONY : draw_polygon.cpp.s

geofunctions.o: geofunctions.cpp.o
.PHONY : geofunctions.o

# target to build an object file
geofunctions.cpp.o:
	$(MAKE) -f CMakeFiles/DrawPolygon.dir/build.make CMakeFiles/DrawPolygon.dir/geofunctions.cpp.o
	$(MAKE) -f CMakeFiles/PolygonIntersection.dir/build.make CMakeFiles/PolygonIntersection.dir/geofunctions.cpp.o
	$(MAKE) -f CMakeFiles/PolygonUnion.dir/build.make CMakeFiles/PolygonUnion.dir/geofunctions.cpp.o
.PHONY : geofunctions.cpp.o

geofunctions.i: geofunctions.cpp.i
.PHONY : geofunctions.i

# target to preprocess a source file
geofunctions.cpp.i:
	$(MAKE) -f CMakeFiles/DrawPolygon.dir/build.make CMakeFiles/DrawPolygon.dir/geofunctions.cpp.i
	$(MAKE) -f CMakeFiles/PolygonIntersection.dir/build.make CMakeFiles/PolygonIntersection.dir/geofunctions.cpp.i
	$(MAKE) -f CMakeFiles/PolygonUnion.dir/build.make CMakeFiles/PolygonUnion.dir/geofunctions.cpp.i
.PHONY : geofunctions.cpp.i

geofunctions.s: geofunctions.cpp.s
.PHONY : geofunctions.s

# target to generate assembly for a file
geofunctions.cpp.s:
	$(MAKE) -f CMakeFiles/DrawPolygon.dir/build.make CMakeFiles/DrawPolygon.dir/geofunctions.cpp.s
	$(MAKE) -f CMakeFiles/PolygonIntersection.dir/build.make CMakeFiles/PolygonIntersection.dir/geofunctions.cpp.s
	$(MAKE) -f CMakeFiles/PolygonUnion.dir/build.make CMakeFiles/PolygonUnion.dir/geofunctions.cpp.s
.PHONY : geofunctions.cpp.s

polygon_intersection.o: polygon_intersection.cpp.o
.PHONY : polygon_intersection.o

# target to build an object file
polygon_intersection.cpp.o:
	$(MAKE) -f CMakeFiles/PolygonIntersection.dir/build.make CMakeFiles/PolygonIntersection.dir/polygon_intersection.cpp.o
.PHONY : polygon_intersection.cpp.o

polygon_intersection.i: polygon_intersection.cpp.i
.PHONY : polygon_intersection.i

# target to preprocess a source file
polygon_intersection.cpp.i:
	$(MAKE) -f CMakeFiles/PolygonIntersection.dir/build.make CMakeFiles/PolygonIntersection.dir/polygon_intersection.cpp.i
.PHONY : polygon_intersection.cpp.i

polygon_intersection.s: polygon_intersection.cpp.s
.PHONY : polygon_intersection.s

# target to generate assembly for a file
polygon_intersection.cpp.s:
	$(MAKE) -f CMakeFiles/PolygonIntersection.dir/build.make CMakeFiles/PolygonIntersection.dir/polygon_intersection.cpp.s
.PHONY : polygon_intersection.cpp.s

polygon_union.o: polygon_union.cpp.o
.PHONY : polygon_union.o

# target to build an object file
polygon_union.cpp.o:
	$(MAKE) -f CMakeFiles/PolygonUnion.dir/build.make CMakeFiles/PolygonUnion.dir/polygon_union.cpp.o
.PHONY : polygon_union.cpp.o

polygon_union.i: polygon_union.cpp.i
.PHONY : polygon_union.i

# target to preprocess a source file
polygon_union.cpp.i:
	$(MAKE) -f CMakeFiles/PolygonUnion.dir/build.make CMakeFiles/PolygonUnion.dir/polygon_union.cpp.i
.PHONY : polygon_union.cpp.i

polygon_union.s: polygon_union.cpp.s
.PHONY : polygon_union.s

# target to generate assembly for a file
polygon_union.cpp.s:
	$(MAKE) -f CMakeFiles/PolygonUnion.dir/build.make CMakeFiles/PolygonUnion.dir/polygon_union.cpp.s
.PHONY : polygon_union.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... DrawPolygon"
	@echo "... PolygonIntersection"
	@echo "... PolygonUnion"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... draw_polygon.o"
	@echo "... draw_polygon.i"
	@echo "... draw_polygon.s"
	@echo "... geofunctions.o"
	@echo "... geofunctions.i"
	@echo "... geofunctions.s"
	@echo "... polygon_intersection.o"
	@echo "... polygon_intersection.i"
	@echo "... polygon_intersection.s"
	@echo "... polygon_union.o"
	@echo "... polygon_union.i"
	@echo "... polygon_union.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

